In [1]:
from collections.abc import Callable
from typing import Any, TypeVar
from BitVector import BitVector
import numpy as np
import numpy.typing as npt

In [3]:
def convert_str_to_unicode_int_array(key: str) -> npt.NDArray[np.uint8]:
        """Convert string to an array of unicode ints.

        Args:
            key (str): Key string

        Returns:
            npt.NDArray[np.uint8]: array of UNICODE ints of the chars
        """
        return np.array([ord(c) for c in key])

In [8]:
def convert_16_byte_key_to_4x4_array(key: str) -> npt.NDArray[np.uint8]:
    """Convert 16 character key (HAS TO BE 16 character KEY) to a 4x4 column major matrix of
    4 4-character words, whose UNICODE numbers are stored in the matrix.

    Args:
        key (str): 16 byte keys

    Returns:
        npt.NDArray[np.uint8]: 2D column wise matrix, each column having the UNICODE number of a 4 
        character word
    """

    words = [convert_str_to_unicode_int_array(key[i:i+4]) for i in range(0, len(key), 4)]
    return np.array(words).T

In [9]:
a = convert_16_byte_key_to_4x4_array("Thats my Kung Fu")
print(a)
a.shape

[[ 84 115  32 103]
 [104  32  75  32]
 [ 97 109 117  70]
 [116 121 110 117]]


(4, 4)

In [10]:
hex_func = np.vectorize(hex)
print(hex_func(a))

[['0x54' '0x73' '0x20' '0x67']
 ['0x68' '0x20' '0x4b' '0x20']
 ['0x61' '0x6d' '0x75' '0x46']
 ['0x74' '0x79' '0x6e' '0x75']]
